"""Add resource type-specific metadata fields

Revision ID: ed984dd3e6d5
Revises: 6e291233e745
Create Date: 2025-11-22 21:00:51.205252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed984dd3e6d5'
down_revision = '6e291233e745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('room_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('printer_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('color_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('printer_model', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('gender_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('gender_type')
        batch_op.drop_column('title')
        batch_op.drop_column('email')
        batch_op.drop_column('printer_model')
        batch_op.drop_column('color_type')
        batch_op.drop_column('printer_name')
        batch_op.drop_column('capacity')
        batch_op.drop_column('room_type')
        batch_op.drop_column('room_number')

    # ### end Alembic commands ###
